### ISSUE TITLE
Conflucting rules: no-extra-parens and unicorn/no-nested-ternary

### ISSUE THREAD

**Issue by davelosert** [thenativeweb/eslint-config-es#355]
When using nested ternary operators (it is not nice, I know - but well), there are two rules:
`no-extra-parens`  and `unicorn/no-nested-ternary`.

The former says not to put parenses around the second ternary, the latter say to do so.

E.g.:

```javascript
// fullfills no-extra-parens
const withoutParens = first ? 'first' : second ? 'second' : 'third'

// Fulfills no-nested-ternary
const withParens = first ? 'first' : (second ? : 'second' : 'third');
```

**Comment by goloroden** [comment]
Thanks for bringing up this issue 😊

However, if you do not use nested ternary, you shouldn't have the problem with the extra parentheses anyway, should you?

IOW: I think this is fine the way it is, because if you stick to the rule you don't have any problems, but if you do, inconsistent things may happen, but then you decided to break the rules anyway.

Having said that, @davelosert, would you still consider this to be an issue?

**Comment by yeldiRium** [comment]
I agree with @goloroden here - if you want the nested ternaries, you can disable the eslint rules to achieve your goal, which is - as you, @davelosert, said yourself - not desirable in itself, because nested ternary.

Can we close this @davelosert?

**Comment by davelosert** [comment]
The issue is that it is hard to work around this if you want to break the rules once. 

But sure, I understand your point and so I'm closing this issue. 🙂
