### ISSUE TITLE
Beispiel & Aufruf

### ISSUE THREAD

**Issue by SoftwareDesign-Solution** [thenativeweb/eslint-config-es#391]
Ich hab folgende Ergänzungswünsche der Readme zu diesem Paket.

1. Beispiel einer .eslintrc.json mit rules, wie man diese auch deaktivieren kann. Hab den Aufbau im Projekt "tlse2021-fullstack-testen" (https://github.com/thenativeweb/tlse2021-fullstack-testen/blob/main/frontend/.eslintrc.json) gefunden.

**.eslintrc.json**

`{
  "root": true,
  "extends": [
    "es/browser"
  ],
  "parserOptions": {
    "sourceType": "module"
  },
  "rules": {
    "linebreak-style": "off",
    "@typescript-eslint/indent": "off",
    "class-methods-use-this": "off",
    "padded-blocks": "off"
  }
}`

2. In der Readme steht am Ende der Befehl "npm run analyse". Wenn man das Paket "roboter" installiert, kann man den Befehl nicht aufrufen. Es muss die package.json angepasst werden.

**scripts in package.json erweitern**
`"analyse": "eslint \"**/*.ts\" --ignore-path .eslintignore",`

**Comment by goloroden** [comment]
Hey @SoftwareDesign-Solution 👋 

I'm going to switch to English, as this is our language of choice for publicly discussed issues.

Regarding number 2, this is a misunderstanding, I guess: This part of the documentation refers to the question how to analyse the `eslint-config-es` package itself. And in its `package.json` file the appropriate line is added, but of course this does not apply to your projects. For your projects it's up to you to configure running ESLint in whatever you want to run it.

Regarding number 1, since here the ESLint default way of overriding rules of a shared configuration applies, we have not documented it explicitly, but I agree that it would be a good idea to at least give a hint on how to do this in the documentation. Will add a link 👍

**Comment by goloroden** [comment]
Fixed in #393
