### ISSUE TITLE
peer dependencies need to be explicitely added in yarn projects

### ISSUE THREAD

**Issue by phoefflin** [thenativeweb/eslint-config-es#465]
Starting with eslint-config-es v4  it's not sufficient  to install only eslint and eslint-config-es in yarn projects anymore. In addition all peerDependencies need to be added explicitly. To my understanding the reason is the different handling of peerDependencies between yarn and npm, version 3 did work for yarn and npm because it did not use peerDependencies.

Could the peer dependencies be moved back to to make the plugin work with yarn again or are there any downsides I'm not aware of?

Example install output:

```
yarn install v1.22.17
        warning package.json: No license field
        warning eslint-es@0.1.0: No license field
        [1/4] Resolving packages...
        [2/4] Fetching packages...
        [3/4] Linking dependencies...
        warning " > eslint-config-es@4.1.0" has unmet peer dependency "@typescript-eslint/eslint-plugin@5.3.0".
        warning " > eslint-config-es@4.1.0" has unmet peer dependency "@typescript-eslint/parser@5.4.0".
        warning " > eslint-config-es@4.1.0" has unmet peer dependency "eslint-plugin-eslint-comments@3.2.0".
        warning " > eslint-config-es@4.1.0" has unmet peer dependency "eslint-plugin-extended@0.2.0".
        warning " > eslint-config-es@4.1.0" has unmet peer dependency "eslint-plugin-mocha@9.0.0".
        warning " > eslint-config-es@4.1.0" has unmet peer dependency "eslint-plugin-react@7.27.1".
        warning " > eslint-config-es@4.1.0" has unmet peer dependency "eslint-plugin-unicorn@37.0.1".
```

package.json used:
```
{
  "name": "eslint-deps",
  "version": "0.1.0",
  "dependencies": {
    "eslint-config-es": "^4.1.0",
    "eslint": "^8.8.0",
    "typescript": "^4.5.5"
  }
}
```

Downgrading to version 3 works for both yarn and npm, example:
```
{
  "name": "eslint-deps",
  "version": "0.1.0",
  "dependencies": {
    "eslint": "^7.32.0",
    "eslint-config-es": "^3.31.0",
    "typescript": "^4.5.5"
  }
}
```

**Comment by phoefflin** [comment]
Or as an alternative to #466 add a comment to the readme that peer deps need to be installed seperately with yarn? `npx install-peerdeps --dev eslint-config-es` worked for me.

**Comment by goloroden** [comment]
Sorry for not having replied yet 😞

We actually had a reason to change this behavior, to make things work in combination with another package of us ([roboter](https://github.com/thenativeweb/roboter/)). We typically do not use `eslint-config-es` without `roboter`, and we don't use Yarn at all.

So while I understand your issue, we're probably not going to change this (as, from at least a specific point of view, Yarn differs from the "default" behavior defined by npm, which is the de-facto industry standard).

Having said that it would make more sense to add a hint to the `README.md` file. However, again, since this is caused by Yarn where it differs from the standard this leads to the situation where we have to check for Yarn compatibility in the future without having any need for this.

So we are probably not going to change anything about this.
